services:
  # ----------------------------------------------------
  # 1. SERVICIO DE APLICACIÓN WEB (PHP-Apache)
  # ----------------------------------------------------
  web:
    # Construye la imagen usando el Dockerfile creado
    build:
      context: ./docker/php
    container_name: gestion-apache
    restart: unless-stopped
    # Mapea la carpeta local 'app' al directorio de trabajo del contenedor
    volumes:
      - ./src:/var/www/html
    # Expone el puerto 80 del contenedor al puerto 80 del host
    ports:
      - "80:80"

    depends_on:
      - db
    # Conecta a la red interna
    networks:
      - gestion_net

  # ----------------------------------------------------
  # 2. SERVICIO DE BASE DE DATOS (MySQL)
  # ----------------------------------------------------
  db:
    image: mysql:8.0
    container_name: gestion-mysql
    restart: unless-stopped
    environment:
      # Variables de entorno de MySQL. ¡Cambia las contraseñas!
      MYSQL_ROOT_PASSWORD: pasword
      MYSQL_DATABASE: almacen
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # Mapea un volumen para persistir los datos de la base de datos
    volumes:
      - gestion_dbdata:/var/lib/mysql
    networks:
      - gestion_net

  # ----------------------------------------------------
  # 3. SERVICIO DE GESTIÓN DE BASES DE DATOS (phpMyAdmin)
  # ----------------------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gestion-phpmyadmin
    restart: unless-stopped
    # Mapea el puerto 8080 del host al 80 del phpMyAdmin
    ports:
      - "8080:80"
    environment:
      # El host es el nombre del servicio Docker de la base de datos
      PMA_HOST: db
      # El puerto de MySQL dentro de la red Docker
      PMA_PORT: 3306 
    depends_on:
      - db
    networks:
      - gestion_net


# ----------------------------------------------------
# 5. REDES Y VOLÚMENES
# ----------------------------------------------------
networks:
  # Red interna para que los contenedores se comuniquen entre sí por nombre
  gestion_net:
    driver: bridge

volumes:
  # Volumen para persistir los datos de MySQL
  gestion_dbdata: